server:
  port: 8888


spring:
  application.name: gateway-service
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: service-test
          uri: lb://service-backend
          #uri: http://localhost:8080
          predicates:
            Path=/api/v1/price/**
          filters:
            - AuthFilter
